# conda environment file for the project. Install it with:
# conda env create -f environment.yml
name: medio
channels:
  - anaconda
  - conda-forge
dependencies:
  - python >= 3.6
  - numpy >= 1.18.1
  - nibabel >= 3.0.2
  - pydicom >= 2.0.0
  - pip >= 20.1.1
  - pip:
      - itk >= 5.2rc2
      - dicom-numpy >= 0.4.0
