[project]
name = "medio"
description = "Medical images I/O Python package"
authors = [
    { name= "RSIP Vision", email= "info@rsipvision.com" },
]
maintainers = [
    { name= "Elazar Cohen", email= "elazar@rsipvision.com" },
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/RSIP-Vision/medio"
keywords = ["medical-images", "IO", "itk", "nibabel", "pydicom"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Image Processing",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules",
#    "Typing :: Typed",  # TODO: Add typing support
]
requires-python = ">=3.7"
dependencies = [
    "itk>=5.1.2",
    "nibabel>=3.2.1",
    "pydicom>=2.1.2",
    "dicom-numpy>= 0.5.0, < 1",
    'numpy>=1.22.2; python_version >= "3.8"',
    'numpy>=1.21.5; python_version>= "3.7"',
]
dynamic = ["version"]

[tool.hatch.version]
path = "medio/__init__.py"

[project.optional-dependencies]
dev = [
    "black>=22.1.0"
]

[project.urls]
"Homepage" = "https://github.com/RSIP-Vision/medio"
"Bug Tracker" = "https://github.com/RSIP-Vision/medio/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[build.targets.sdist]
exclude = [ 
    "/tests"
]

[build.targets.wheel]
packages = ["medio"]

[tool.hatch.envs.test]
dependencies = [
  "coverage[toml]",
  "pytest",
  "pytest-cov",
  "pytest-mock",
]

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.hatch.envs.test.scripts]
cov = "pytest --cov-config=pyproject.toml --cov=pkg --cov=tests"
run = "run-coverage --no-cov"

[tool.hatch.envs.style]
python = "3.10"
detached = true
dependencies = [
  "flake8",
  "black",
  "isort",
]
[tool.hatch.envs.style.scripts]
check = [
  "flake8 .",
  "black --check --diff .",
  "isort --check-only --diff .",
]
fmt = [
  "isort .",
  "black .",
  "check",
]